---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: flask-3.8
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: postgres-secret-config
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: password
            - name: db_name
              value: flaskapi
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"